import { VenueCandidate } from '../types/index.js';

export const mockVenues: VenueCandidate[] = [
  // --- YEMEK / FOOD ---
  {
    id: 'venue-1',
    title: 'Smash & Craft Burger Lab',
    category: 'burger',
    categoryNameTr: 'Burger & Sokak Lezzeti',
    type: 'food',
    description: 'Özel tereyağlı brioche ekmeği ve 21 gün kuru dinlendirilmiş dana döş köftesiyle hazırlanan gurme smash burgerler.',
    address: 'Moda Cad. No:44, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9875,
    lng: 29.0289,
    priceLevel: 2,
    rating: 4.8,
    reviewCount: 420,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    tags: ['Gurme Burger', 'Truffle Fries', 'Craft İçecekler', 'Samimi'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['solo', 'group'],
    defaultCooldownDays: 3,
    openingHours: '12:00 - 23:30',
    phoneNumber: '+90 216 414 55 22',
    isIndoor: true,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'moderate'
  },
  {
    id: 'venue-2',
    title: 'Trattoria Bella Napoli',
    category: 'italyan',
    categoryNameTr: 'İtalyan & Taş Fırın Pizza',
    type: 'food',
    description: 'Odun ateşinde pişen Napoliten pizzalar, el yapımı taze tagliatelle ve tiramisu ile otantik İtalyan deneyimi.',
    address: 'Bağdat Caddesi No: 218, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9632,
    lng: 29.0684,
    priceLevel: 3,
    rating: 4.9,
    reviewCount: 680,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    tags: ['Napoliten Pizza', 'Taze Makarna', 'Şarap Seçkisi', 'Mum Işığı'],
    isVegetarianFriendly: true,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'romantic',
    suitableFor: ['couple', 'solo', 'group'],
    defaultCooldownDays: 4,
    openingHours: '12:30 - 23:00',
    phoneNumber: '+90 216 350 78 90',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'busy'
  },
  {
    id: 'venue-3',
    title: 'Közde Ocakbaşı & Zırh Kebabı',
    category: 'kebap',
    categoryNameTr: 'Geleneksel Kebap & Meze',
    type: 'food',
    description: 'Zırhla çekilmiş kuzu Adana kebap, közlenmiş patlıcanlı ali nazik ve çıtır lahmacun şöleni.',
    address: 'Halaskargazi Cad. No: 87, Şişli',
    district: 'Şişli',
    city: 'İstanbul',
    lat: 41.0543,
    lng: 28.9892,
    priceLevel: 3,
    rating: 4.7,
    reviewCount: 910,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    tags: ['Zırh Kebabı', 'Köz Meze', 'Fındık Lahmacun', 'Geleneksel'],
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'cozy',
    suitableFor: ['group', 'couple'],
    defaultCooldownDays: 4,
    openingHours: '11:30 - 00:00',
    phoneNumber: '+90 212 230 45 67',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'busy'
  },
  {
    id: 'venue-4',
    title: 'Tokyo Ramen & Sushi Bar',
    category: 'uzakdogu',
    categoryNameTr: 'Uzak Doğu & Sushi/Ramen',
    type: 'food',
    description: '12 saat kaynatılmış tonkotsu ve miso ramen brothları, çıtır gyoza ve taze somon nigiri.',
    address: 'Karaköy Rıhtım Sok. No: 12, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0245,
    lng: 28.9774,
    priceLevel: 3,
    rating: 4.8,
    reviewCount: 540,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    tags: ['Otantik Ramen', 'Gyoza', 'Sushi', 'Japon Çayı'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: false,
    isRomantic: true,
    vibe: 'trendy',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 5,
    openingHours: '12:00 - 22:30',
    phoneNumber: '+90 212 243 11 99',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'moderate'
  },
  {
    id: 'venue-5',
    title: 'Toprak & Zeytin Ev Yemekleri',
    category: 'ev_yemekleri',
    categoryNameTr: 'Anne Usulü Ev Yemekleri',
    type: 'food',
    description: 'Günlük taze pişen zeytinyağlılar, hünkar beğendi, kuru fasulye pilav ve sıcacık mercimek çorbası.',
    address: 'Ihlamurdere Cad. No: 56, Beşiktaş',
    district: 'Beşiktaş',
    city: 'İstanbul',
    lat: 41.0438,
    lng: 29.0065,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    tags: ['Zeytinyağlı', 'Tencere Yemeği', 'Bütçe Dostu', 'Hafif'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'cozy',
    suitableFor: ['solo', 'group'],
    defaultCooldownDays: 2,
    openingHours: '11:00 - 20:30',
    phoneNumber: '+90 212 258 33 10',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'quiet'
  },
  {
    id: 'venue-6',
    title: 'Roast & Bloom Specialty Coffee & Cheesecake',
    category: 'kahve_tatli',
    categoryNameTr: 'Nitelikli Kahve & Tatlı',
    type: 'food',
    description: '3. dalga taze kavrum çekirdekler, akışkan San Sebastian cheesecake, lotus kruvasan ve ferah çalışma ortamı.',
    address: 'Caferağa Mah. Şevki Bey Sok. No: 18, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9852,
    lng: 29.0271,
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 790,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    tags: ['Flat White', 'San Sebastian', 'Kruvasan', 'Kitap/Sohbet'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 1,
    openingHours: '08:30 - 23:00',
    phoneNumber: '+90 216 348 90 12',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'moderate'
  },
  {
    id: 'venue-7',
    title: 'Green Leaf Vegan & Bowl Kitchen',
    category: 'vejetaryen',
    categoryNameTr: 'Vegan / Vejetaryen & Sağlıklı',
    type: 'food',
    description: 'Protein dolu kinoa kaseleri, avokadolu smoothie bowl, falafel wrap ve şekersiz raw tatlılar.',
    address: 'Tomtom Mah. Yeni Çarşı Cad. No: 29, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0315,
    lng: 28.9768,
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    tags: ['Buddha Bowl', 'Vegan Tatlı', 'Detoks', 'Glutensiz'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 2,
    openingHours: '10:00 - 21:00',
    phoneNumber: '+90 212 249 70 80',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'quiet'
  },
  {
    id: 'venue-8',
    title: 'Tako & Quesadilla Street House',
    category: 'sokak_lezzetleri',
    categoryNameTr: 'Meksika & Çıtır Sokak Lezzetleri',
    type: 'food',
    description: 'Yavaş pişmiş dana birria taco, eritme peynirli quesadilla, çıtır churros ve acı sos barı.',
    address: 'Akaretler Süleyman Seba Cad. No: 41, Beşiktaş',
    district: 'Beşiktaş',
    city: 'İstanbul',
    lat: 41.0412,
    lng: 29.0019,
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 460,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    tags: ['Birria Taco', 'Nachos', 'Churros', 'Hızlı & Lezzetli'],
    isVegetarianFriendly: true,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['solo', 'group'],
    defaultCooldownDays: 3,
    openingHours: '12:00 - 01:00',
    phoneNumber: '+90 212 260 14 15',
    isIndoor: true,
    hasTerrace: true,
    isCozy: false,
    busynessLevel: 'busy'
  },
  {
    id: 'venue-9',
    title: 'Yakamoz Balıkçı & Ege Mezeleri',
    category: 'balik',
    categoryNameTr: 'Ege Mutfağı & Balık Meze',
    type: 'food',
    description: 'Günlük taze deniz levreği, tereyağlı karides güveç, deniz börülcesi, fava ve Boğaz manzarası.',
    address: 'Kuzguncuk Çarşı Cad. No: 15, Üsküdar',
    district: 'Üsküdar',
    city: 'İstanbul',
    lat: 41.0345,
    lng: 29.0305,
    priceLevel: 4,
    rating: 4.8,
    reviewCount: 610,
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    tags: ['Boğaz Manzarası', 'Taze Balık', 'Girit Ezmesi', 'Özel Akşam'],
    isVegetarianFriendly: true,
    isVeganFriendly: false,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'romantic',
    suitableFor: ['couple', 'group'],
    defaultCooldownDays: 6,
    openingHours: '13:00 - 00:00',
    phoneNumber: '+90 216 341 88 00',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'busy'
  },
  {
    id: 'venue-10',
    title: 'Moda Dondurmacı & Magnolia Craft',
    category: 'kahve_tatli',
    categoryNameTr: 'Artisan Dondurma & Magnolia',
    type: 'food',
    description: 'Gerçek keçi sütlü artisan dondurma, muzlu oreolu magnolia ve sıcak çikolata lezzeti.',
    address: 'Moda İskelesi Sok. No: 8, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9845,
    lng: 29.0279,
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 510,
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80',
    tags: ['Artisan Dondurma', 'Magnolia', 'Moda Sahil', 'Tatlı Molası'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 1,
    openingHours: '10:00 - 00:30',
    phoneNumber: '+90 216 336 20 10',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'moderate'
  },

  // --- AKTİVİTE & MEKAN / ACTIVITIES ---
  {
    id: 'act-1',
    title: 'Enigma Kilitli Oda & Escape Game',
    category: 'eglence_oyun',
    categoryNameTr: 'Kaçış Oyunu & Zeka Bulmacası',
    type: 'activity',
    description: '60 dakikalık sürükleyici gizemli dedektiflik ve macera odası. Ekip çalışmasıyla şifreleri çözün ve kaçın!',
    address: 'İstiklal Cad. Mis Sokak No: 8, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0360,
    lng: 28.9830,
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1511871893557-c674ffc0993e?auto=format&fit=crop&w=800&q=80',
    tags: ['Grup Oyunu', 'Adrenalin', 'Gizem', 'Ekip Ruhu'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'adventurous',
    suitableFor: ['group', 'couple'],
    defaultCooldownDays: 10,
    openingHours: '11:00 - 00:30',
    phoneNumber: '+90 212 245 67 89',
    isIndoor: true,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-2',
    title: 'Neon Strike Bowling & Arcade Arena',
    category: 'eglence_oyun',
    categoryNameTr: 'Bowling & Retro Arcade',
    type: 'activity',
    description: 'Ultra-modern 12 hatlı neon bowling pisti, hava hokeyi, retro arcade makineleri ve atıştırmalık barı.',
    address: 'Akasya AVM Kat 3, Acıbadem, Üsküdar',
    district: 'Üsküdar',
    city: 'İstanbul',
    lat: 40.9998,
    lng: 29.0558,
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 880,
    imageUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80',
    tags: ['Neon Bowling', 'Air Hockey', 'Grup Eğlencesi', 'Rekabet'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['group', 'couple'],
    defaultCooldownDays: 5,
    openingHours: '10:00 - 23:00',
    phoneNumber: '+90 216 428 10 20',
    isIndoor: true,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'busy'
  },
  {
    id: 'act-3',
    title: 'Sahne Moda Stand-up & Butik Tiyatro',
    category: 'sinema_tiyatro',
    categoryNameTr: 'Stand-up Komedi & Tiyatro',
    type: 'activity',
    description: 'Haftanın her günü kahkaha dolu stand-up geceleri, doğaçlama gösteriler ve bağımsız tiyatro oyunları.',
    address: 'Moda Cad. Ferit Tek Sok. No: 12, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9840,
    lng: 29.0310,
    priceLevel: 3,
    rating: 4.9,
    reviewCount: 390,
    imageUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=800&q=80',
    tags: ['Stand-Up', 'Komedi', 'Canlı Gösteri', 'Eğlenceli Akşam'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'energetic',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 7,
    openingHours: '19:00 - 23:30',
    phoneNumber: '+90 216 330 50 60',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-4',
    title: 'Kil & Kahve Sanat Seramik Atölyesi',
    category: 'kultur_sanat',
    categoryNameTr: 'Seramik & Resim Atölyesi',
    type: 'activity',
    description: 'Kendi seramik kupanızı veya tabağınızı şekillendirin, boyayın ve fırınlatın. Çiftler ve arkadaş grupları için harika yaratıcı deneyim.',
    address: 'Kuloğlu Mah. Ağa Hamamı Sok. No: 7, Cihangir, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0332,
    lng: 28.9815,
    priceLevel: 3,
    rating: 4.9,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    tags: ['Çömlek Tornası', 'Seramik Boyama', 'Yaratıcı', 'Huzurlu'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'cozy',
    suitableFor: ['couple', 'solo', 'group'],
    defaultCooldownDays: 14,
    openingHours: '11:00 - 20:00',
    phoneNumber: '+90 212 244 80 15',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'quiet'
  },
  {
    id: 'act-5',
    title: 'Caddebostan Sahil Günbatımı & Bisiklet Turu',
    category: 'spor_outdoor',
    categoryNameTr: 'Açık Hava & Sahil Bisiklet/Piknik',
    type: 'activity',
    description: 'Marmara Denizi ve Adalar manzarası eşliğinde kiralık bisiklet veya scooter turu, çimlerde piknik örtüsü ve termos kahve keyfi.',
    address: 'Caddebostan Sahil Yolu, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9610,
    lng: 29.0590,
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 1520,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    tags: ['Açık Hava', 'Piknik', 'Günbatımı', 'Bütçe Dostu', 'Bisiklet'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 2,
    openingHours: '24 Saat Açık',
    phoneNumber: '-',
    isIndoor: false,
    hasTerrace: true,
    isCozy: false,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-6',
    title: 'Dice & Meeples Board Game Kafe',
    category: 'kafe_sohbet',
    categoryNameTr: 'Kutu Oyunları & Masaüstü Oyunlar',
    type: 'activity',
    description: '300+ kutu oyunu (Catan, Codenames, Ticket to Ride, Dixit), uzman oyun anlatıcıları ve lezzetli kahveler.',
    address: 'Bahariye Cad. Dr. İhsan Ünlüer Sok. No: 14, Kadıköy',
    district: 'Kadıköy',
    city: 'İstanbul',
    lat: 40.9880,
    lng: 29.0340,
    priceLevel: 2,
    rating: 4.8,
    reviewCount: 670,
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    tags: ['Catan', 'Kutu Oyunu', 'Grup Sohbeti', 'Çok Eğlenceli'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'cozy',
    suitableFor: ['group', 'couple'],
    defaultCooldownDays: 4,
    openingHours: '12:00 - 00:00',
    phoneNumber: '+90 216 345 88 12',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-7',
    title: 'Jazz & Velvet Akustik Canlı Müzik Bar',
    category: 'gece_hayati',
    categoryNameTr: 'Canlı Caz & Kokteyl Bar',
    type: 'activity',
    description: 'Usta caz müzisyenlerinden canlı trompet ve piyano dinletisi, imza kokteyller ve loş samimi atmosfer.',
    address: 'Asmalımescit Sok. No: 22, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0308,
    lng: 28.9745,
    priceLevel: 3,
    rating: 4.9,
    reviewCount: 440,
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80',
    tags: ['Canlı Caz', 'İmza Kokteyller', 'Loş Atmosfer', 'Romantik'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'romantic',
    suitableFor: ['couple', 'solo', 'group'],
    defaultCooldownDays: 6,
    openingHours: '18:00 - 02:00',
    phoneNumber: '+90 212 251 12 34',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-8',
    title: 'Apex Padel Club & Halısaha Arena',
    category: 'spor_outdoor',
    categoryNameTr: 'Padel Tenis & Halısaha',
    type: 'activity',
    description: 'Yeni nesil trend Padel tenis kortları, profesyonel raket kiralama ve 4e4 veya 7ye7 maç imkanı.',
    address: 'Vadi Kemer Yolu No: 3, Sarıyer',
    district: 'Sarıyer',
    city: 'İstanbul',
    lat: 41.1085,
    lng: 28.9912,
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 350,
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=800&q=80',
    tags: ['Padel Tenis', 'Spor', 'Grup Maçı', 'Yüksek Enerji'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['group'],
    defaultCooldownDays: 3,
    openingHours: '09:00 - 00:00',
    phoneNumber: '+90 212 332 90 90',
    isIndoor: false,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'busy'
  },
  {
    id: 'act-9',
    title: 'Karaköy Vault Kokteyl & Chill Lounge',
    category: 'gece_hayati',
    categoryNameTr: 'Butik Kokteyl & Loş Müzik',
    type: 'activity',
    description: 'Tarihi tonozlu binada özel reçeteli artisan kokteyller, ambient müzik ve huzurlu bir akşam kapanışı.',
    address: 'Karaköy Bankalar Cad. No: 19, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0255,
    lng: 28.9765,
    priceLevel: 3,
    rating: 4.8,
    reviewCount: 380,
    imageUrl: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80',
    tags: ['Artisan Kokteyl', 'Tarihi Tonoz', 'Ambient Müzik', 'Chill'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['couple', 'solo', 'group'],
    defaultCooldownDays: 4,
    openingHours: '17:00 - 02:00',
    phoneNumber: '+90 212 249 19 20',
    isIndoor: true,
    hasTerrace: true,
    isCozy: true,
    busynessLevel: 'quiet'
  },
  {
    id: 'act-10',
    title: 'Zen Spa & Thai Masaj Merkezi',
    category: 'spa_rahatlama',
    categoryNameTr: 'Spa & Masaj / Rahatlama',
    type: 'activity',
    description: 'Haftanın yorgunluğunu atmak için aromaterapi yağlarıyla uygulanan geleneksel Thai masajı ve sauna keyfi.',
    address: 'Levent Mah. Çalıkuşu Sok. No: 5, Beşiktaş',
    district: 'Levent',
    city: 'İstanbul',
    lat: 41.0820,
    lng: 29.0145,
    priceLevel: 4,
    rating: 4.9,
    reviewCount: 320,
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80',
    tags: ['Masaj', 'Spa', 'Aromaterapi', 'Rahatlama', 'Huzur'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple'],
    defaultCooldownDays: 14,
    openingHours: '10:00 - 22:00',
    phoneNumber: '+90 212 300 44 55',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'quiet'
  },
  {
    id: 'act-11',
    title: 'Bomonti Antika Pazarı',
    category: 'alisveris_pazar',
    categoryNameTr: 'Alışveriş & Antika Pazarı',
    type: 'activity',
    description: 'Pazar günleri kurulan, nostaljik eşyalar, plaklar, ikinci el kıyafetler ve harika sokak lezzetleri bulabileceğiniz pazar.',
    address: 'Bomontiada Yanı, Şişli',
    district: 'Şişli',
    city: 'İstanbul',
    lat: 41.0590,
    lng: 28.9790,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 890,
    imageUrl: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=800&q=80',
    tags: ['Antika', 'Plak', 'İkinci El', 'Kalabalık', 'Nostalji'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 30,
    openingHours: '09:00 - 18:00 (Sadece Pazar)',
    phoneNumber: '-',
    isIndoor: false,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'busy'
  },
  {
    id: 'act-12',
    title: 'Belgrad Ormanı Doğa Yürüyüşü',
    category: 'spor_outdoor',
    categoryNameTr: 'Trekking & Doğa Yürüyüşü',
    type: 'activity',
    description: 'Neşet Suyu parkurunda 6 km\\'lik doğa yürüyüşü, göl kenarında dinlenme ve bol oksijen.',
    address: 'Belgrad Ormanı Neşet Suyu Tabiat Parkı, Sarıyer',
    district: 'Sarıyer',
    city: 'İstanbul',
    lat: 41.1712,
    lng: 28.9699,
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 1250,
    imageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=800&q=80',
    tags: ['Orman', 'Yürüyüş', 'Temiz Hava', 'Doğa', 'Spor'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 10,
    openingHours: '24 Saat Açık',
    phoneNumber: '-',
    isIndoor: false,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-13',
    title: 'VR Arena Sanal Gerçeklik',
    category: 'eglence_oyun',
    categoryNameTr: 'Sanal Gerçeklik & VR',
    type: 'activity',
    description: 'Arkadaşlarınızla aynı anda savaşabileceğiniz veya dünyayı kurtarabileceğiniz serbest dolaşımlı multiplayer VR deneyimi.',
    address: 'Cevahir AVM Kat 5, Şişli',
    district: 'Şişli',
    city: 'İstanbul',
    lat: 41.0625,
    lng: 28.9926,
    priceLevel: 3,
    rating: 4.7,
    reviewCount: 410,
    imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=800&q=80',
    tags: ['VR', 'Teknoloji', 'Grup Oyunu', 'Adrenalin'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: false,
    vibe: 'energetic',
    suitableFor: ['group', 'couple'],
    defaultCooldownDays: 14,
    openingHours: '10:00 - 22:00',
    phoneNumber: '+90 212 380 99 99',
    isIndoor: true,
    hasTerrace: false,
    isCozy: false,
    busynessLevel: 'moderate'
  },
  {
    id: 'act-14',
    title: 'İstanbul Modern Sanat Müzesi',
    category: 'kultur_sanat',
    categoryNameTr: 'Müze & Modern Sanat',
    type: 'activity',
    description: 'Renzo Piano tasarımı yeni binasında çağdaş sanat sergileri, boğaz manzaralı terası ve geniş kütüphanesi.',
    address: 'Kılıçali Paşa Mah. Tophane İskele Cad. No:1, Beyoğlu',
    district: 'Beyoğlu',
    city: 'İstanbul',
    lat: 41.0263,
    lng: 28.9818,
    priceLevel: 2,
    rating: 4.9,
    reviewCount: 1540,
    imageUrl: 'https://images.unsplash.com/photo-1562624475-cb3e7f451fdb?auto=format&fit=crop&w=800&q=80',
    tags: ['Sanat', 'Sergi', 'Tasarım', 'Boğaz Manzarası', 'Sakin'],
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isGlutenFreeFriendly: true,
    isRomantic: true,
    vibe: 'chill',
    suitableFor: ['solo', 'couple', 'group'],
    defaultCooldownDays: 30,
    openingHours: '10:00 - 18:00',
    phoneNumber: '+90 212 334 73 00',
    isIndoor: true,
    hasTerrace: true,
    isCozy: false,
    busynessLevel: 'busy'
  },
  {
    id: 'venue-11',
    title: 'Eataly Mutfak Atölyesi',
    category: 'workshop',
    categoryNameTr: 'Gastronomi & Yemek Kursu',
    type: 'activity',
    description: 'İtalyan şefler eşliğinde taze makarna yapımı, pizza atölyesi ve şarap tadımı. Etkinlik sonrası kendi yaptığınızı yeme keyfi!',
    address: 'Zorlu Center Meydan Katı, Beşiktaş',
    district: 'Beşiktaş',
    city: 'İstanbul',
    lat: 41.0664,
    lng: 29.0175,
    priceLevel: 4,
    rating: 4.8,
    reviewCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80',
    tags: ['Workshop', 'Makarna Yapımı', 'Eğlenceli', 'Öğretici'],
    isVegetarianFriendly: true,
    isVeganFriendly: false,
    isGlutenFreeFriendly: false,
    isRomantic: true,
    vibe: 'energetic',
    suitableFor: ['couple', 'solo', 'group'],
    defaultCooldownDays: 20,
    openingHours: '19:00 - 22:00 (Etkinlik Saatleri)',
    phoneNumber: '+90 212 336 66 00',
    isIndoor: true,
    hasTerrace: false,
    isCozy: true,
    busynessLevel: 'moderate'
  }
];
